// packages/nextjs/example/src/app/page.tsx
'use client'

import { useState } from 'react'
import { useI18n } from '@ldesign/i18n-nextjs'
import { i18n } from '@/lib/i18n'

export default function Home() {
  const { t, locale, setLocale } = useI18n(i18n)
  const [count, setCount] = useState(0)

  return (
    <div style={{ padding: '2rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1>{t('welcome')}</h1>
      <p>{t('description')}</p>
      
      <div style={{ marginTop: '2rem' }}>
        <button onClick={() => setLocale(locale === 'en' ? 'zh' : 'en')}>
          {t('switchLanguage')}
        </button>
        <span style={{ marginLeft: '1rem' }}>
          Current: {locale}
        </span>
      </div>

      <div style={{ marginTop: '2rem' }}>
        <h2>{t('counter')}: {count}</h2>
        <button onClick={() => setCount(count + 1)}>
          {t('increment')}
        </button>
        <button onClick={() => setCount(count - 1)} style={{ marginLeft: '1rem' }}>
          {t('decrement')}
        </button>
      </div>
    </div>
  )
}

// packages/vue/example/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from '@ldesign/i18n-vue'

const { t, locale, setLocale } = useI18n()
const count = ref(0)

function toggleLanguage() {
  setLocale(locale.value === 'en' ? 'zh' : 'en')
}
</script>

<template>
  <div :style="{ padding: '2rem', fontFamily: 'system-ui, sans-serif' }">
    <h1>{{ t('welcome') }}</h1>
    <p>{{ t('description') }}</p>
    
    <div :style="{ marginTop: '2rem' }">
      <button @click="toggleLanguage">
        {{ t('switchLanguage') }}
      </button>
      <span :style="{ marginLeft: '1rem' }">
        Current: {{ locale }}
      </span>
    </div>

    <div :style="{ marginTop: '2rem' }">
      <h2>{{ t('counter') }}: {{ count }}</h2>
      <button @click="count++">
        {{ t('increment') }}
      </button>
      <button @click="count--" :style="{ marginLeft: '1rem' }">
        {{ t('decrement') }}
      </button>
    </div>
  </div>
</template>
