// packages/preact/src/components/Trans.tsx
/**
 * @ldesign/i18n-preact - Trans
 */

import { useI18n } from '../hooks'

export interface TransProps {
  i18nKey: string
  params?: Record<string, any>
  fallback?: string
}

export function Trans({ i18nKey, params, fallback }: TransProps) {
  const i18n = useI18n()
  const text = i18n.t(i18nKey, params) || fallback || i18nKey
  return <>{text}</>
}

// packages/sveltekit/src/components/Trans.svelte
<script lang="ts">
  import { getContext } from 'svelte'
  import type { I18nStore } from '../stores'

  export let key: string
  export let params: Record<string, any> = {}
  export let fallback: string = key

  const i18n = getContext<I18nStore>('i18n')
  
  $: text = i18n ? i18n.t(key, params) : fallback
</script>

{text}
