// packages/svelte/src/components/LocaleSwitcher.svelte
<script lang="ts">
  import type { Locale } from '@ldesign/i18n-core'
  import { getI18nContext } from '../utils/context'

  /**
   * Custom locales to display (optional)
   */
  export let locales: Locale[] | undefined = undefined

  /**
   * Custom labels for locales
   */
  export let labels: Record<Locale, string> | undefined = undefined

  // Get i18n from context
  const i18n = getI18nContext()

  // Get available locales
  $: availableLocales = locales || $i18n.availableLocales

  // Get current locale
  $: currentLocale = $i18n.locale

  // Handle locale change
  async function handleChange(event: Event) {
    const target = event.target as HTMLSelectElement
    const newLocale = target.value as Locale
    await i18n.setLocale(newLocale)
  }

  // Get label for locale
  function getLabel(locale: Locale): string {
    if (labels && labels[locale]) {
      return labels[locale]
    }
    return locale
  }
</script>

<select value={$currentLocale} on:change={handleChange}>
  {#each availableLocales as locale}
    <option value={locale}>{getLabel(locale)}</option>
  {/each}
</select>

// packages/solid/src/components/LocaleSwitcher.tsx
/**
 * LocaleSwitcher Component for Solid
 */

import type { Locale } from '@ldesign/i18n-core'
import type { Component } from 'solid-js'
import { For } from 'solid-js'
import { useLocale } from '../primitives/useLocale'

export interface LocaleSwitcherProps {
  /**
   * Custom locales to display (optional)
   */
  locales?: Locale[]

  /**
   * Custom labels for locales
   */
  labels?: Record<Locale, string>
}

/**
 * LocaleSwitcher component
 * 
 * @example
 * ```tsx
 * <LocaleSwitcher />
 * <LocaleSwitcher 
 *   locales={['zh-CN', 'en']} 
 *   labels={{ 'zh-CN': '中文', 'en': 'English' }}
 * />
 * ```
 */
export const LocaleSwitcher: Component<LocaleSwitcherProps> = (props) => {
  const { locale, availableLocales, setLocale } = useLocale()

  const displayLocales = () => props.locales || availableLocales()

  const getLabel = (loc: Locale): string => {
    if (props.labels && props.labels[loc]) {
      return props.labels[loc]
    }
    return loc
  }

  const handleChange = async (event: Event) => {
    const target = event.target as HTMLSelectElement
    const newLocale = target.value as Locale
    await setLocale(newLocale)
  }

  return (
    <select value={locale()} onChange={handleChange}>
      <For each={displayLocales()}>
        {(loc) => <option value={loc}>{getLabel(loc)}</option>}
      </For>
    </select>
  )
}
