// packages/svelte/src/components/Trans.svelte
<script lang="ts">
  import type { InterpolationParams } from '@ldesign/i18n-core'
  import { getI18nContext } from '../utils/context'

  /**
   * Translation key
   */
  export let keypath: string

  /**
   * Interpolation parameters
   */
  export let params: InterpolationParams | undefined = undefined

  /**
   * Locale override
   */
  export let locale: string | undefined = undefined

  /**
   * Tag name for wrapper element
   */
  export let tag: string = 'span'

  // Get i18n from context
  const i18n = getI18nContext()

  // Reactive translation
  $: translatedText = i18n.t(keypath, { params, locale })
</script>

<svelte:element this={tag}>
  {translatedText}
</svelte:element>

// packages/solid/src/components/Trans.tsx
/**
 * Trans Component for Solid
 */

import type { InterpolationParams } from '@ldesign/i18n-core'
import type { Component } from 'solid-js'
import { useI18n } from '../primitives/useI18n'

export interface TransProps {
  /**
   * Translation key
   */
  keypath: string

  /**
   * Interpolation parameters
   */
  params?: InterpolationParams

  /**
   * Locale override
   */
  locale?: string

  /**
   * Tag name for wrapper element
   */
  tag?: keyof JSX.IntrinsicElements
}

/**
 * Trans component for translation
 * 
 * @example
 * ```tsx
 * <Trans keypath="welcome" params={{ name: 'User' }} />
 * <Trans keypath="title" tag="h1" />
 * ```
 */
export const Trans: Component<TransProps> = (props) => {
  const { t } = useI18n()
  const Tag = props.tag || 'span'

  return (
    <Tag>
      {t(props.keypath, { params: props.params, locale: props.locale })}
    </Tag>
  )
}
