// packages/solid/src/components/LocaleSwitcher.tsx
/**
 * LocaleSwitcher Component for Solid
 */

import type { Locale } from '@ldesign/i18n-core'
import type { Component } from 'solid-js'
import { For } from 'solid-js'
import { useLocale } from '../primitives/useLocale'

export interface LocaleSwitcherProps {
  /**
   * Custom locales to display (optional)
   */
  locales?: Locale[]

  /**
   * Custom labels for locales
   */
  labels?: Record<Locale, string>
}

/**
 * LocaleSwitcher component
 * 
 * @example
 * ```tsx
 * <LocaleSwitcher />
 * <LocaleSwitcher 
 *   locales={['zh-CN', 'en']} 
 *   labels={{ 'zh-CN': '中文', 'en': 'English' }}
 * />
 * ```
 */
export const LocaleSwitcher: Component<LocaleSwitcherProps> = (props) => {
  const { locale, availableLocales, setLocale } = useLocale()

  const displayLocales = () => props.locales || availableLocales()

  const getLabel = (loc: Locale): string => {
    if (props.labels && props.labels[loc]) {
      return props.labels[loc]
    }
    return loc
  }

  const handleChange = async (event: Event) => {
    const target = event.target as HTMLSelectElement
    const newLocale = target.value as Locale
    await setLocale(newLocale)
  }

  return (
    <select value={locale()} onChange={handleChange}>
      <For each={displayLocales()}>
        {(loc) => <option value={loc}>{getLabel(loc)}</option>}
      </For>
    </select>
  )
}

// packages/angular/src/components/locale-switcher.component.ts
/**
 * LocaleSwitcherComponent - Angular component for locale switching
 */

import { Component, Input } from '@angular/core'
import type { Locale } from '@ldesign/i18n-core'
import { I18nService } from '../services/i18n.service'

/**
 * Locale switcher component
 * 
 * @example
 * ```html
 * <ldesign-locale-switcher></ldesign-locale-switcher>
 * <ldesign-locale-switcher [locales]="['zh-CN', 'en']"></ldesign-locale-switcher>
 * ```
 */
@Component({
  selector: 'ldesign-locale-switcher',
  template: `
    <select [value]="i18nService.locale" (change)="onChange($event)">
      <option *ngFor="let loc of displayLocales" [value]="loc">
        {{ getLabel(loc) }}
      </option>
    </select>
  `,
  standalone: true
})
export class LocaleSwitcherComponent {
  @Input() locales?: Locale[]
  @Input() labels?: Record<Locale, string>

  constructor(public i18nService: I18nService) { }

  get displayLocales(): Locale[] {
    return this.locales || this.i18nService.availableLocales
  }

  getLabel(locale: Locale): string {
    if (this.labels && this.labels[locale]) {
      return this.labels[locale]
    }
    return locale
  }

  async onChange(event: Event): Promise<void> {
    const target = event.target as HTMLSelectElement
    const newLocale = target.value as Locale
    await this.i18nService.setLocale(newLocale)
  }
}
