// packages/angular/examples/src/app/app.component.ts
import { Component } from '@angular/core'
import { I18nService } from '@ldesign/i18n-angular'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  userName = 'Angular'
  itemCount = 5
  today = new Date()
  price = 1234567.89

  constructor(public i18n: I18nService) { }

  incrementCount(): void {
    this.itemCount++
  }

  decrementCount(): void {
    this.itemCount = Math.max(0, this.itemCount - 1)
  }
}


<div class="app">
  <header class="header">
    <h1>@ldesign/i18n-angular 功能演示</h1>
    <div class="locale-switcher">
      <button (click)="i18n.setLocale('zh-CN')">中文</button>
      <button (click)="i18n.setLocale('en')">English</button>
      <button (click)="i18n.setLocale('ja')">日本語</button>
      <span class="current-locale">当前: {{ i18n.locale }}</span>
    </div>
  </header>

  <main class="content">
    <section class="demo-section">
      <h2>1. 基础翻译 (Service)</h2>
      <div class="demo-item">
        <p><strong>i18n.t('hello'):</strong> {{ i18n.t('hello') }}</p>
        <p><strong>i18n.t('about'):</strong> {{ i18n.t('about') }}</p>
      </div>
    </section>

    <section class="demo-section">
      <h2>2. 翻译管道 (Pipe)</h2>
      <div class="demo-item">
        <p><strong>'hello' | translate:</strong> {{ 'hello' | translate }}</p>
        <p><strong>'welcome' | translate:</strong> {{ 'welcome' | translate: { name: userName } }}</p>
      </div>
    </section>

    <section class="demo-section">
      <h2>3. 翻译指令 (Directive)</h2>
      <div class="demo-item">
        <div i18nTranslate="hello"></div>
        <div [i18nTranslate]="'welcome'" [i18nTranslateParams]="{ name: userName }"></div>
      </div>
    </section>

    <section class="demo-section">
      <h2>4. 复数化</h2>
      <div class="demo-item">
        <div class="controls">
          <button (click)="decrementCount()">-</button>
          <span class="count">{{ itemCount }}</span>
          <button (click)="incrementCount()">+</button>
        </div>
        <p>{{ itemCount }} {{ 'items' | plural: itemCount }}</p>
      </div>
    </section>

    <section class="demo-section">
      <h2>5. 格式化</h2>
      <div class="demo-item">
        <p>日期: {{ today | i18nDate: 'long' }}</p>
        <p>数字: {{ price | i18nNumber }}</p>
        <p>货币: {{ 99.99 | i18nNumber: 'currency' }}</p>
        <p>百分比: {{ 0.85 | i18nNumber: 'percent' }}</p>
      </div>
    </section>

    <section class="demo-section">
      <h2>6. RxJS Observable</h2>
      <div class="demo-item">
        <p>当前语言 (Observable): {{ i18n.locale$ | async }}</p>
        <p>翻译 (Observable): {{ i18n.t$('hello') | async }}</p>
      </div>
    </section>

    <section class="demo-section">
      <h2>7. 功能特性</h2>
      <div class="demo-item">
        <ul>
          <li>{{ i18n.t('features.services') }}</li>
          <li>{{ i18n.t('features.pipes') }}</li>
          <li>{{ i18n.t('features.directives') }}</li>
          <li>{{ i18n.t('features.rxjs') }}</li>
        </ul>
      </div>
    </section>
  </main>
</div>

// packages/react/examples/src/App.tsx
import { useState } from 'react'
import { useI18n, Trans } from '@ldesign/i18n-react'

function App() {
  const { t, tc, d, n, locale, setLocale } = useI18n()
  const [userName, setUserName] = useState('React')
  const [itemCount, setItemCount] = useState(5)

  return (
    <div className="app">
      <header className="header">
        <h1>@ldesign/i18n-react 功能演示</h1>
        <div className="locale-switcher">
          <button onClick={() => setLocale('zh-CN')}>中文</button>
          <button onClick={() => setLocale('en')}>English</button>
          <button onClick={() => setLocale('ja')}>日本語</button>
          <span className="current-locale">当前: {locale}</span>
        </div>
      </header>

      <main className="content">
        <section className="demo-section">
          <h2>1. 基础翻译 (useI18n)</h2>
          <div className="demo-item">
            <p><strong>t('hello'):</strong> {t('hello')}</p>
            <p><strong>t('about'):</strong> {t('about')}</p>
          </div>
        </section>

        <section className="demo-section">
          <h2>2. 参数插值</h2>
          <div className="demo-item">
            <input
              value={userName}
              onChange={(e) => setUserName(e.target.value)}
              placeholder="输入名字"
            />
            <p>{t('welcome', { name: userName })}</p>
          </div>
        </section>

        <section className="demo-section">
          <h2>3. Trans 组件</h2>
          <div className="demo-item">
            <Trans keypath="welcome" params={{ name: userName }} />
          </div>
        </section>

        <section className="demo-section">
          <h2>4. 复数化</h2>
          <div className="demo-item">
            <div className="controls">
              <button onClick={() => setItemCount(Math.max(0, itemCount - 1))}>-</button>
              <span className="count">{itemCount}</span>
              <button onClick={() => setItemCount(itemCount + 1)}>+</button>
            </div>
            <p>{itemCount} {tc('items', itemCount)}</p>
          </div>
        </section>

        <section className="demo-section">
          <h2>5. 格式化</h2>
          <div className="demo-item">
            <p>日期: {d(new Date(), 'long')}</p>
            <p>数字: {n(1234567.89)}</p>
            <p>货币: {n(99.99, 'currency')}</p>
          </div>
        </section>

        <section className="demo-section">
          <h2>6. 功能特性</h2>
          <div className="demo-item">
            <ul>
              <li>{t('features.hooks')}</li>
              <li>{t('features.components')}</li>
              <li>{t('features.hoc')}</li>
            </ul>
          </div>
        </section>
      </main>
    </div>
  )
}

export default App
